# Dependabot configuration for automated dependency updates
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm (server)
  - package-ecosystem: "npm"
    directory: "/tripvar-server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "mfarsx"
    commit-message:
      prefix: "chore(deps-server)"
      include: "scope"
    labels:
      - "dependencies"
      - "server"
      - "automated"
    ignore:
      # Ignore major version updates for stability
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for npm (client)
  - package-ecosystem: "npm"
    directory: "/tripvar-client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "mfarsx"
    commit-message:
      prefix: "chore(deps-client)"
      include: "scope"
    labels:
      - "dependencies"
      - "client"
      - "automated"
    ignore:
      # Ignore major version updates for stability
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/tripvar-server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    reviewers:
      - "mfarsx"
    commit-message:
      prefix: "chore(docker)"
    labels:
      - "docker"
      - "automated"

  - package-ecosystem: "docker"
    directory: "/tripvar-client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    reviewers:
      - "mfarsx"
    commit-message:
      prefix: "chore(docker)"
    labels:
      - "docker"
      - "automated"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
    reviewers:
      - "mfarsx"
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "ci"
      - "automated"
