services:
  mongodb:
    image: mongo:7.0
    container_name: tripvar-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=tripvar
    command: ${MONGO_COMMAND:-mongod --quiet --logpath /dev/null}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    networks:
      - app-network

  redis:
    image: redis:7.2-alpine
    container_name: tripvar-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ${REDIS_COMMAND:-redis-server --appendonly yes --loglevel warning}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    networks:
      - app-network

  server:
    build:
      context: ./tripvar-server
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}
    container_name: tripvar-server
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./tripvar-server/.env${ENV_SUFFIX:-}
    volumes:
      - ${VOLUME_MOUNT:-./tripvar-server:/usr/src/app}
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=${LOG_LEVEL:-warn}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    networks:
      - app-network

  client:
    build:
      context: ./tripvar-client
      dockerfile: Dockerfile.dev
    container_name: tripvar-client
    restart: unless-stopped
    ports:
      - "${CLIENT_PORT:-5173}:${CLIENT_PORT:-5173}"
    env_file:
      - ./tripvar-client/.env${ENV_SUFFIX:-}
    volumes:
      - ${VOLUME_MOUNT:-./tripvar-client:/app}
      - /app/node_modules  # Prevent node_modules from being overwritten
    depends_on:
      - server
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
      - VITE_ENABLE_DEBUG_LOGGING=true
      - VITE_ENABLE_ERROR_REPORTING=true
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: