services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "local"
      options:
        mode: "non-blocking"
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "local"
      options:
        mode: "non-blocking"
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./ai-service:/app
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_NAME=tripvar_db
      - DEBUG=true
      - LOG_LEVEL=debug
      - LLM_HOST=host.docker.internal
      - LLM_PORT=1234
      - LLM_PROTOCOL=http
      - REDIS_URL=redis://redis:6379/0
      - HOST=0.0.0.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "local"
      options:
        mode: "non-blocking"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health/db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - ai-service
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - VITE_API_PATH=/api/v1
      - VITE_HOST=true
      - VITE_API_CHANGE_ORIGIN=true
      - VITE_API_SECURE=false
    logging:
      driver: "local"
      options:
        mode: "non-blocking"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    name: mongodb_data
  redis_data:
    name: redis_data
