version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./ai-service:/app
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_NAME=tripvar_db

  client:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - ai-service

networks:
  default:
    driver: bridge

volumes:
  mongodb_data:
    name: mongodb_data
