# Quiet version of docker-compose.yml with minimal logging
services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword123
      - MONGO_INITDB_DATABASE=tripvar
    command: mongod --quiet --logpath /dev/null --logappend
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "none"
    networks:
      - app-network

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "none"
    networks:
      - app-network

  server:
    build: ./tripvar-server
    ports:
      - "8000:8000"
    env_file:
      - ./tripvar-server/.env
    volumes:
      - ./tripvar-server:/usr/src/app
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DEBUG=false
      - LOG_LEVEL=warn
      - LLM_HOST=host.docker.internal
      - LLM_PORT=1234
      - LLM_PROTOCOL=http
      - HOST=0.0.0.0
      - NODE_ENV=development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - app-network

  client:
    build:
      context: ./tripvar-client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    env_file:
      - ./tripvar-client/.env
    volumes:
      - ./tripvar-client:/app
      - /app/node_modules
    depends_on:
      server:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - VITE_API_PATH=/api/v1
      - VITE_HOST=0.0.0.0
    logging:
      driver: "none"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    name: mongodb_data
  redis_data:
    name: redis_data