name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 9 * * 1" # Every Monday at 9 AM UTC

jobs:
  security-audit:
    name: Dependency Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Audit server dependencies
        working-directory: ./tripvar-server
        run: npm audit || true
        continue-on-error: true

      - name: Audit client dependencies
        working-directory: ./tripvar-client
        run: npm audit || true
        continue-on-error: true
